-- Script generated by R2Sv2
-- R2Sv2 developed by Luckyxero
 
local Achieve1 = "Fey's Purple Ray" -- The achievement you'd like to get
local Achieve2 = game:GetService("Workspace").achievementParts[Achieve1].Part
local Event = game:GetService("ReplicatedStorage").shared.remotes.achievement
Event:FireServer(Achieve1, Achieve2)
